version: '3.9'
services:
  client:
    build: Client.Finansys/.
    environment:
      NODE_ENV: production
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - db
      - api
  api:
    build: Api.Finansys/.
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports: 
      - "8000:80"
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "numsey#2022"
    ports:
      - "1433:1433"
    volumes:
      - D:\SQLSERVER\data:/var/opt/mssql/data