name: Build & Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}} 
          port: ${{ secrets.SSH_SERVER_PORT }}
          password: ${{secrets.SSH_PASSWORD}} 
          username: ${{ secrets.SSH_USERNAME }} 
          script: |
            rm -rf finansys
            git clone git@github.com:gleidsonbalcazar/finansys.git
            cd finansys
            docker-compose build
            docker-compose up
